### ISSUE TITLE
Display account balance

### ISSUE THREAD

**Issue by ccris02** [Nadro-J/py-subalert#2]
Would it be possible to display the account balance and how much was transferred in $ as well? 
Something like this.

```
1,222.01 $KSM ($218.30 - $266,764) successfully sent to E7ncQKp4xayUoUdpraxBjT7NzLoayLJA4TuPcKKboBkJ5GH

-- [ Details ] ---
Bank Sender balance: 0.00 
Lock Locked: 0.00

Bank Receiver balance: 325.22K ($70,995,526)
Lock Locked: 0.00
```

**Comment by Nadro-J** [comment]
Sure thing :D I'll implement this tonight

**Comment by Nadro-J** [comment]
![image](https://user-images.githubusercontent.com/43568466/127786166-e8936367-4b5d-4122-b650-91ce2d82feb5.png)

**Comment by ccris02** [comment]
Wow, looks great.

**Comment by Nadro-J** [comment]
Just updating repo and setting up for PolkadotTxs :) Had to exclude the -- [ Details ] --- part due to character limitations. Next thing I plan to add is plotting account balance history of the sender/receiver and attaching as a .png to the tweet for even more insightful info, either over 7 days or 14 days.
